# Generated by Django 6.1.1 on 2026-09-15 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_workinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='catalog.master')),
            ],
            options={
                'verbose_name': 'Исключение из расписания',
                'verbose_name_plural': 'Исключения из расписания',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('master', 'date'), name='unique_master_schedule_exception'), models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', True), ('is_closed', True), ('start_time__isnull', True)), models.Q(('end_time__isnull', False), ('is_closed', False), ('start_time__isnull', False)), _connector='OR'), name='schedule_exception_time_consistency')],
            },
        ),
    ]
