# Generated by Django 6.1.1 on 2026-09-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_scheduleexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='catalog.master')),
            ],
            options={
                'verbose_name': 'Блокировка времени',
                'verbose_name_plural': 'Блокировки времени',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
