# Generated by Django 6.1.1 on 2026-09-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_timeblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Плановая продолжительность услуги в минутах.')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('CONFIRMED', 'Подтверждена'), ('CANCELLED', 'Отменена'), ('COMPLETED', 'Завершена')], default='NEW', max_length=20)),
                ('source', models.CharField(choices=[('ONLINE', 'Онлайн'), ('PHONE', 'Телефон'), ('ADMIN', 'Администратор')], default='ONLINE', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
